from typing import Literal

__all__ = [
    "STATE_UNKNOWN",
    "STATE_QUEUED",
    "STATE_INITIALIZING",
    "STATE_RUNNING",
    "STATE_PAUSED",
    "STATE_COMPLETE",
    "STATE_EXECUTOR_ERROR",
    "STATE_SYSTEM_ERROR",
    "STATE_CANCELED",
    "STATE_CANCELING",
    # -----------------------
    "FailureState",
    "FAILURE_STATES",
    "SUCCESS_STATES",
    "TERMINATED_STATES",
]

STATE_UNKNOWN: Literal["UNKNOWN"] = "UNKNOWN"
STATE_QUEUED: Literal["QUEUED"] = "QUEUED"
STATE_INITIALIZING: Literal["INITIALIZING"] = "INITIALIZING"
STATE_RUNNING: Literal["RUNNING"] = "RUNNING"
STATE_PAUSED: Literal["PAUSED"] = "PAUSED"
STATE_COMPLETE: Literal["COMPLETE"] = "COMPLETE"
STATE_EXECUTOR_ERROR: Literal["EXECUTOR_ERROR"] = "EXECUTOR_ERROR"
STATE_SYSTEM_ERROR: Literal["SYSTEM_ERROR"] = "SYSTEM_ERROR"
STATE_CANCELED: Literal["CANCELED"] = "CANCELED"
STATE_CANCELING: Literal["CANCELING"] = "CANCELING"

FailureState = Literal["EXECUTOR_ERROR", "SYSTEM_ERROR"]

FAILURE_STATES = frozenset({STATE_EXECUTOR_ERROR, STATE_SYSTEM_ERROR})
SUCCESS_STATES = frozenset({STATE_COMPLETE})
TERMINATED_STATES = FAILURE_STATES.union(SUCCESS_STATES)
