name: Lint
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        name: Set up Python
        with:
          python-version: "3.10"
      - name: Install Poetry
        run: python -m pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run linter
        run: poetry run flake8 ./bento_wes ./tests
