name: Lint
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install flake8
        run: pip install flake8
      - name: Run linter
        run: flake8 ./bento_wes ./tests
